### ISSUE TITLE
Cannot use sudo as parameter in cmd

### ISSUE THREAD

**Issue by Brownyuan** [hellstein/ssh-rpc-agent#10]
## Project version
* tag: 0.0.4

## Architecture
amd64
## Expected behavior
sudo usermod -aG sudo xxx

**Comment by dorrywhale** [comment]
Fix the issue in [0.1.7](https://github.com/hellstein/ssh-rpc-agent/releases/download/0.1.7/ssh-rpc-agent-0.1.7.zip)
