### ISSUE TITLE
建议 添加 machine.json  tasks.json 模版文件 到releases下载文件里

### ISSUE THREAD

**Issue by able8** [hellstein/ssh-rpc-agent#11]
下载ssh-rpc-agent-0.1.4.zip后，开始配置，发现没有 machine.json  tasks.json 模版文件，到项目源码里才发现，才知道如何配置这个文件。

建议添加文件模版，或项目添加说明格式。

**Comment by dorrywhale** [comment]
It has been resolved in [0.1.6](https://github.com/hellstein/ssh-rpc-agent/releases/download/0.1.6/ssh-rpc-agent-0.1.6.zip)
