### ISSUE TITLE
Error on macOS:    chown: root: illegal group name

### ISSUE THREAD

**Issue by able8** [hellstein/ssh-rpc-agent#13]
macOS:

➜  make config SSHDATA=~/.ssh NAME=rsa
cp -rf ~/.ssh /Users/able/Downloads/agent-3/imageAPI/sshdata.run
sudo chown -R root:root /Users/able/Downloads/agent-3/imageAPI/sshdata.run
Password:
chown: root: illegal group name
make: *** [config] Error 1

add a comment in Makefile `#sudo chown -R root:root $(SDRUNDIR)`, then it works.

**Comment by dorrywhale** [comment]
Would you like to make PR (pull request), that would be great, and it is going to be really helpful to build the community process for us.

**Comment by able8** [comment]
OK.
